Cart and order data persistence on the server side
composable-com/composable-ui pull request #21
Opened 2023-10-30 13:52 UTC by marcin-slezak

## Background

Voucherify is a Promotion Engine which allows marketing teams to run digital promotions like coupons, gift cards, referrals, bundles and loyalty. As the headless commerce solution and Mach Alliance member, we want to integrate Composable UI with Voucherify to help our community better understand how to build promotion features efficiently in the composable commerce storefront.

I appreciate your effort to build and share the Composable UI accelerator. I really enjoy working on this application; it's flexible and well-designed. Still, I encountered a problem which I need to solve first before I will be able to continue building this integration (as a part of another future PR).

## Problem
To show a little more advanced digital promotion scenarios in the storefront, we need functionality that allows users to add more than one product to the cart in Composable UI. Unfortunately, currently as the user :
- we see in the cart only one recently added product; adding the next cart item overwrites the existing product in the cart,
- cart reset to the default state (one `Venture Daypack` product) after refreshing the page in the browser,
- a new order is not built on the top of the current user cart.

The reason for this behaviour is an example `commerce-generic` service that manages the cart and orders data without any data persistence on the server side. Because of `commerce-generic` implementation simplification, this service can not keep consistent responses in a series of `createCart`, `addCartItem`, `updateCartItem`, and `getCart` requests. 

## Solution

We have prepared a Pull Request to Composable UI repository, where we have improved `commerce-generic` service by adding cart and order data file-based persistence, so it allows users to manage products in the cart more freely. 

Summary of the changes:
- we have used the `node-persist` package, which provides a minimalistic API to persist data in JSON files and reduce code complexity,
- we use a folder path for temporary files defined by the OS as a location of JSON files with cart and order data,
- we have tested changes on both local development and for apps deployed on Vercel. Please remember that Vercel allows saving temporary files in the `/tmp` folder. From our experience, this lasts long enough (10+ minutes) to keep a nice user experience. 
- we could not test changes on Netlify as currently, we are facing a bug in Netlify's `next-runtime` library: [Link](https://github.com/netlify/next-runtime/issues/2323)
- all changes are part of `commerce-generic` service, except:
	- a few checkout components as we need additionally to provide the `cartId` param to the `createOrder`  request
	- `composable-ui/src/utils/__mocks__/api.ts` - we have added missing mocked data fixing test `src/components/__tests__/home-page.test.tsx`, which fails on `main` branch
- we have not changed the mocked available product data, so there are no other required changes, e.g. in the Algolia integration.

Here is a video that shows the difference in behaviour. On the left side, we have changes from this PR; on the right side application before changes:

https://github.com/voucherifyio/composable-ui/assets/35666945/859c11d7-df74-40a3-b9ca-6815b7e64a94

2023-10-31 17:28 UTC, dannytlake commented
@marcin-slezak I was able to successfully deploy on Netlify, see deployment https://composable-ui-voucherify.netlify.app/

Can you please try setting the [`PNPM_FLAGS`](https://docs.netlify.com/configure-builds/manage-dependencies/#pnpm) environment variable on your Netlify deploy to see if it resolves the issue (you'll need to manually trigger a redeploy after setting it)?

PNPM_FLAGS = --shamefully-hoist

![image](https://github.com/composable-com/composable-ui/assets/13950845/40248aa8-ed9b-4da5-afcd-5208f0e775ad)

This variable gets set automatically through our [1 click deploy to Netlify link](https://app.netlify.com/start/deploy?repository=https://github.com/composable-com/composable-ui&base=composable-ui#PNPM_FLAGS=--shamefully-hoist), however maybe we need to update the docs to surface this when doing a manual deploy to Netlify from a forked repository. Please let me know if this resolves the Netlify issue.

2023-10-31 17:58 UTC, dannytlake requested changes

2023-10-31 17:58 UTC, dannytlake commented on packages/commerce-generic/src/data/persit.ts
To strongly illustrate that this is a mocked data storage layer:

1. Please rename this to `mock-storage.ts`
2. Add a comment in here about how this is purely for demonstration purposes and should never be used in a Production environment. Add a note about the quality of persistence provided, related to how this leverages storing data in serverless functions that can be destroyed and recreated at any time by the Cloud Provider (ie Vercel or Netlify), which will cause any user with a working cart with items to start again from scratch.

2023-11-10 08:49 UTC, marcin-slezak commented
@dannytlake Thank you for your suggestion about [PNPM_FLAGS](https://docs.netlify.com/configure-builds/manage-dependencies/#pnpm)! I successfully deployed on Netlify using your advice (https://calm-otter-6d91de.netlify.app/). I can confirm that storage-mock works the same way as on Vercel. I also applied the suggested changes.

2023-11-14 20:17 UTC, merged